service: serverlessbmsproject

provider:
  name: aws
  runtime: nodejs12.x
  profile: bmsAccount
  region: eu-central-1
  environment:
    tableNameConnection: ${self:custom.tableNameConnection}
    tableNameSystem: ${self:custom.tableNameSystem}
    tableNameData: ${self:custom.tableNameData}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: '*'

custom:
  tableNameConnection: Connections
  tableNameSystem: Systems
  tableNameData: PrimaryData

functions:
  websocket-connect:
    handler: lambdas/websockets/connect.handler
    events:
      - websocket:
          route: $connect
  websocket-disconnect:
    handler: lambdas/websockets/disconnect.handler
    events:
      - websocket:
          route: $disconnect
  websocket-default:
    handler: lambdas/websockets/default.handler
    events:
      - websocket:
          route: $default
  websocket-system:
    handler: lambdas/websockets/system.handler
    events:
      - websocket:
          route: system
  websocket-primary-data:
    handler: lambdas/websockets/primary-data.handler
    events:
      - websocket:
          route: primary-data

resources:
  Resources:
    ConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableNameConnection}
        AttributeDefinitions:
          - AttributeName: ConnectionId
            AttributeType: S
        KeySchema:
          - AttributeName: ConnectionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    SystemsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableNameSystem}
        AttributeDefinitions:
          - AttributeName: BMSHWRSN
            AttributeType: S
        KeySchema:
          - AttributeName: BMSHWRSN
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    PrimaryDataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableNameData}
        AttributeDefinitions:
          - AttributeName: BMSHWRSN
            AttributeType: S
          - AttributeName: Id
            AttributeType: S
        KeySchema:
          - AttributeName: BMSHWRSN
            KeyType: HASH
          - AttributeName: Id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
