DROP TABLE IF EXISTS MetaData;
DROP TABLE IF EXISTS PrimaryData;
DROP TABLE IF EXISTS SyncLog;
DROP TABLE IF EXISTS "System";

CREATE TABLE "System" (
	"Id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"ConfigVer"	TEXT NOT NULL,
	"BusinessUnit"	TEXT NOT NULL,
	"EdgeHWRSN"	TEXT NOT NULL,
	"EdgeSWRVer"	TEXT NOT NULL,
	"BMSHWRSN"	TEXT NOT NULL UNIQUE,
	"BMSSWRVer"	TEXT NOT NULL
);

CREATE TABLE "MetaData" (
	"Key"	TEXT NOT NULL,
	"Value"	TEXT NOT NULL,
	"Unit"	TEXT
);

CREATE TABLE "PrimaryData" (
	"Id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"Localtime"	TEXT NOT NULL,
	"HB1"	INTEGER NOT NULL,
	"SOC"	INTEGER NOT NULL,
	"SOCMax"	INTEGER NOT NULL,
	"SOCMin"	INTEGER NOT NULL,
	"IChgLimit"	INTEGER NOT NULL,
	"IDsgLimit"	INTEGER NOT NULL,
	"HB2"	INTEGER NOT NULL,
	"SOH"	INTEGER NOT NULL,
	"OpStatus"	INTEGER NOT NULL,
	"RlyStatus"	INTEGER NOT NULL,
	"VBattery"	INTEGER NOT NULL,
	"IBattery"	INTEGER NOT NULL,
	"VCellMin"	INTEGER NOT NULL,
	"VCellMinID"	INTEGER NOT NULL,
	"VCellMax"	INTEGER NOT NULL,
	"VCellMaxID"	INTEGER NOT NULL,
	"TModMin"	INTEGER NOT NULL,
	"TModAvg"	INTEGER NOT NULL,
	"TModMax"	INTEGER NOT NULL,
	"TModMinID"	INTEGER NOT NULL,
	"TModMaxID"	INTEGER NOT NULL,
	"HIBattery"	INTEGER NOT NULL,
	"reserved"	INTEGER NOT NULL,
	"CreatedAt"	TEXT NOT NULL,
	"SystemId"	INTEGER NOT NULL,
	FOREIGN KEY("SystemId") REFERENCES "System"("Id")
);

CREATE TABLE "SyncLog" (
	"SystemId"	INTEGER NOT NULL,
	"PrimaryDataId"	INTEGER NOT NULL,
	"SyncDate"	TEXT,
	"SyncComment"	TEXT,
	"Processing"	INTEGER NOT NULL DEFAULT 0,
	"Processed"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("SystemId","PrimaryDataId")
);

INSERT INTO "System"  (ConfigVer, BusinessUnit, EdgeHWRSN, EdgeSWRVer, BMSHWRSN, BMSSWRVer) VALUES ('1.2.0', 'eTransport', 'Ax_12598324', 'Ax_2.5.3',
'G2_2.4.1', 'G2_3.2.0');

INSERT INTO PrimaryData  (
    Localtime,
	HB1,
	SOC,
	SOCMax,
	SOCMin,
	IChgLimit,
	IDsgLimit,
	HB2,
	SOH,
	OpStatus,
	RlyStatus,
	VBattery,
	IBattery,
	VCellMin,
	VCellMinID,
	VCellMax,
	VCellMaxID,
	TModMin,
	TModAvg,
	TModMax,
	TModMinID,
	TModMaxID,
	HIBattery,
	reserved,
	CreatedAt,
	SystemId
) VALUES (
    '13.05.2019 08:09:05',
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    date('now'),
    1    
),
(
    '14.06.2019 09:09:05',
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    date('now'),
    1    
),
(
    '15.07.2019 10:09:05',
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    date('now'),
    1    
);

INSERT INTO  SyncLog (SystemId, PrimaryDataId) VALUES (1, 1);
INSERT INTO SyncLog (SystemId, PrimaryDataId) VALUES (1, 2);
INSERT INTO SyncLog (SystemId, PrimaryDataId) VALUES (1, 3);

INSERT INTO MetaData (Key, Value, UNIT) VALUES
('Localtime',	'Edge device local time', NULL),
('HB1','Hearbeat 1','%'),
('SOC','State of charge','%'),
('SOCMax','State of charge Max','%'),
('SOCMin','State of charge Min','%'),
('IChgLimit','Charge Current Limit','100mA'),
('IDsgLimit','Discharge Current Limit','100mA'),
('HB2','Hearbeat 2','%'),
('SOH','State of Health','%'),
('OpStatus','Operation Status','%'),
('RlyStatus','Contactor Status','%'),
('VBattery','Stack voltage','0.1V'),
('IBattery','Stack current','0.1A'),
('VCellMin','Cell Voltage Min','mV'),
('VCellMinID','Cell Voltage Min ID','-'),
('VCellMax','Cell Voltage Max','mV'),
('VCellMaxID','Cell Voltage Max ID','-'),
('TModMin','Module Temp Min','0.1°C'),
('TModAvg','Module Temp Avg','0.1V'),
('TModMax','Module Temp Max','0.1°C'),
('TModMinID','Module Temp Min ID','-'),
('TModMaxID','Cell Voltage Max ID','-'),
('HIBattery','High Resulution Current','1mA'),
('reserved','Reserveed Parameter','-');