service: serverlessbmsproject

provider:
  name: aws
  runtime: nodejs12.x
  profile: bmsAccount
  region: eu-central-1
  environment:
    tableNameConnection: ${self:custom.tableNameConnection}
    tableNameCanMapping: ${self:custom.tableNameCanMapping}
    tableNameMetaData: ${self:custom.tableNameMetaData}
    tableNamePrimaryData: ${self:custom.tableNamePrimaryData}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: '*'

custom:
  tableNameConnection: Connections
  tableNameCanMapping: CanMapping
  tableNameMetaData: MetaData
  tableNamePrimaryData: PrimaryData

functions:
  websocket-connect:
    handler: lambdas/websockets/connect.handler
    events:
      - websocket:
          route: $connect
  websocket-disconnect:
    handler: lambdas/websockets/disconnect.handler
    events:
      - websocket:
          route: $disconnect
  websocket-default:
    handler: lambdas/websockets/default.handler
    events:
      - websocket:
          route: $default
  websocket-can-mapping:
    handler: lambdas/websockets/can-mapping.handler
    events:
      - websocket:
          route: can-mapping
  websocket-meta-data:
    handler: lambdas/websockets/meta-data.handler
    events:
      - websocket:
          route: meta-data
  websocket-primary-data:
    handler: lambdas/websockets/primary-data.handler
    events:
      - websocket:
          route: primary-data

resources:
  Resources:
    ConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableNameConnection}
        AttributeDefinitions:
          - AttributeName: ConnectionId
            AttributeType: S
        KeySchema:
          - AttributeName: ConnectionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    CanMappingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableNameCanMapping}
        AttributeDefinitions:
          - AttributeName: BMSHWRSN
            AttributeType: S
        KeySchema:
          - AttributeName: BMSHWRSN
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    MataDataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableNameMetaData}
        AttributeDefinitions:
          - AttributeName: BMSHWRSN
            AttributeType: S
        KeySchema:
          - AttributeName: BMSHWRSN
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    PrimaryDataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableNamePrimaryData}
        AttributeDefinitions:
          - AttributeName: BMSHWRSN
            AttributeType: S
          - AttributeName: ReceivedDateTime
            AttributeType: S
        KeySchema:
          - AttributeName: BMSHWRSN
            KeyType: HASH
          - AttributeName: ReceivedDateTime
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
