DROP TABLE IF EXISTS MetaData;
DROP TABLE IF EXISTS PrimaryData;
DROP TABLE IF EXISTS SyncLog;
DROP TABLE IF EXISTS CANMapping;

CREATE TABLE "MetaData" (
    "Cluster"   TEXT NOT NULL,
	"Key"	TEXT NOT NULL,
	"Value"	TEXT NOT NULL
);

CREATE TABLE "CANMapping" (
	"Key"	TEXT NOT NULL,
	"Value"	TEXT NOT NULL,
	"Unit"	TEXT
);

CREATE TABLE "PrimaryData" (
	"Id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"Localtime"	TEXT NOT NULL,
	"HB1"	INTEGER NOT NULL,
	"SOC"	INTEGER NOT NULL,
	"SOCMax"	INTEGER NOT NULL,
	"SOCMin"	INTEGER NOT NULL,
	"IChgLimit"	INTEGER NOT NULL,
	"IDsgLimit"	INTEGER NOT NULL,
	"HB2"	INTEGER NOT NULL,
	"SOH"	INTEGER NOT NULL,
    "SOHMin"	INTEGER NOT NULL,
    "SOHMax"	INTEGER NOT NULL,
	"OpStatus"	INTEGER NOT NULL,
	"RlyStatus"	INTEGER NOT NULL,
	"VBattery"	INTEGER NOT NULL,
	"IBattery"	INTEGER NOT NULL,
	"VCellMin"	INTEGER NOT NULL,
	"VCellMinID"	INTEGER NOT NULL,
	"VCellMax"	INTEGER NOT NULL,
	"VCellMaxID"	INTEGER NOT NULL,
	"TModMin"	INTEGER NOT NULL,
	"TModAvg"	INTEGER NOT NULL,
	"TModMax"	INTEGER NOT NULL,
	"TModMinID"	INTEGER NOT NULL,
	"TModMaxID"	INTEGER NOT NULL,
	"HIBattery"	INTEGER NOT NULL,
	"reserved"	INTEGER NOT NULL,
    "Alarms"	INTEGER NOT NULL,
	"Warnings"	INTEGER NOT NULL,
	"SystemId"	TEXT NOT NULL,
    "CreatedAt" TEXT NOT NULL
);

CREATE TABLE "SyncLog" (
	"SystemId"	TEXT NOT NULL,
	"PrimaryDataId"	INTEGER NOT NULL,
	"SyncDate"	TEXT,
	"SyncComment"	TEXT,
	"Processing"	INTEGER NOT NULL DEFAULT 0,
	"Processed"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("SystemId","PrimaryDataId")
);

INSERT INTO MetaData  (Cluster, "Key", "Value") VALUES 
('Identification',	'ConfigVer',	'1.2.0'),
('Identification',	'BusinessUnit', 'eAGV'),
('Identification',	'EdgeHWRSN', 'Ax_12598324'),
('Identification',	'EdgeSWRVer', 'Ax_2.5.3'),
('Identification',	'BMSHWRSN', 'EigerC63B124'),
('Identification',	'BMSSWRVer', 'EigerC63S456'),
('Identification',	'CANMappingVer', 'C63CANV100'),
('SystemDescription',	'Technology', 'LTO'),
('SystemDescription',	'ModConfig', '6s4p'),
('SystemDescription',	'StrConfig', '6S6s4p'),
('SystemDescription',	'BatConfig', '1P6S6s4p'),
('SystemDescription',	'NomVoltage', '80V'),
('SystemDescription',	'NomCapacity', '120Ah'),
('ProductInfo',	'Customer', 'Generic_1'),
('ProductInfo',	'Location', 'somewhere'),
('ProductInfo',	'FabricationDate', '01.01.2020'),
('ProductInfo',	'InstallationDate', '01.01.2020'),
('ProductInfo',	'ContactMail', 'support@leclanche.com'),
('ProductInfo',	'ContactTel', '004121021021021'),
('CANInfo',	'CANChannel', '1'),
('CANInfo',	'CANSpeed', '500'),
('CANInfo',	'CANTimeout', '10');

INSERT INTO PrimaryData  (
    Localtime,
	HB1,
	SOC,
	SOCMax,
	SOCMin,
	IChgLimit,
	IDsgLimit,
	HB2,
	SOH,
    SOHMax,
    SOHMin,
	OpStatus,
	RlyStatus,
	VBattery,
	IBattery,
	VCellMin,
	VCellMinID,
	VCellMax,
	VCellMaxID,
	TModMin,
	TModAvg,
	TModMax,
	TModMinID,
	TModMaxID,
	HIBattery,
	reserved,
    Alarms,
    Warnings,
	CreatedAt,
	SystemId
) VALUES (
    '13.05.2019 08:09:05',
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    date('now'),
    'EigerC63B124'   
),
(
    '14.06.2019 09:09:05',
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    date('now'),
    'EigerC63B124'    
),
(
    '15.07.2019 10:09:05',
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    date('now'),
    'EigerC63B124'    
);

INSERT INTO CANMapping (Key, Value, UNIT) VALUES
('HB1','Hearbeat 1','%'),
('SOC','State of charge','%'),
('SOCMax','State of charge Max','%'),
('SOCMin','State of charge Min','%'),
('IChgLimit','Charge Current Limit','100mA'),
('IDsgLimit','Discharge Current Limit','100mA'),
('HB2','Hearbeat 2','%'),
('SOH','State of Health','%'),
('SOHMax','State of Health Max','%'),
('SOHMin','State of Health Min','%'),
('OpStatus','Operation Status','%'),
('RlyStatus','Contactor Status','%'),
('VBattery','Stack voltage','0.1V'),
('IBattery','Stack current','0.1A'),
('VCellMin','Cell Voltage Min','mV'),
('VCellMinID','Cell Voltage Min ID','-'),
('VCellMax','Cell Voltage Max','mV'),
('VCellMaxID','Cell Voltage Max ID','-'),
('TModMin','Module Temp Min','0.1°C'),
('TModAvg','Module Temp Avg','0.1V'),
('TModMax','Module Temp Max','0.1°C'),
('TModMinID','Module Temp Min ID','-'),
('TModMaxID','Cell Voltage Max ID','-'),
('HIBattery','High Resulution Current','1mA'),
('reserved','Reserveed Parameter','-'),
('Alarms',	'Battery Alarms',	'bitFields'),
('Warnings', 'Battery Warnings', 'bitFields');